name: Build Kivy App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade cython virtualenv

    - name: Setup Buildozer
      run: |
        git clone https://github.com/kivy/buildozer
        cd buildozer
        python setup.py build
        pip install -e .
        cd ..

    - name: Build Kivy App
      run: |
        cd path_to_your_kivy_project
        buildozer init
        buildozer android debug
